## Redes Neurais Artificiais 2020.1

**Disciplina**: Redes Neurais Artificiais 2020.1  
**Professora**: Elloá B. Guedes (ebgcosta@uea.edu.br)  
**Github**: http://github.com/elloa  
        

Levando em conta a base de dados **_Forest Cover Type_**, esta terceira parte do Projeto Prático 3 diz respeito à proposição e avaliação de múltiplas redes neurais artificiais do tipo feedforward multilayer perceptron para o problema da classificação multi-classe da cobertura florestal em uma área do Roosevelt National Forest.

## Testando Redes Neurais sem os Atributos Categórios

1. Abra a base de dados em questão
2. Elimine todas as colunas relativas aos atributos categóricos
3. Armazene o atributo alvo em uma variável y e os atributos preditores em uma variável X
4. Efetue uma partição holdout 70/30 com o sklearn, distribuindo os exemplos de maneira aleatória
5. Efetue o escalonamento dos atributos

### Escalonando os atributos

O treinamento de uma rede neural artificial é mais eficiente quando os valores que lhes são fornecidos como entrada são pequenos, pois isto favorece a convergência. Isto é feito escalonando-se todos os atributos para o intervalo [0,1], mas precisa ser feito de maneira cautelosa, para que informações do conjunto de teste não sejam fornecidas no treinamento.

Há duas estratégias para tal escalonamento: normalização e padronização. Ambas possuem características particulares, vantagens e limitações, como é possível ver aqui: https://www.analyticsvidhya.com/blog/2020/04/feature-scaling-machine-learning-normalization-standardization/


No nosso caso, vamos usar a padronização. Assim, com os atributos preditores do treinamento, isto é, X_train, deve-se subtrair a média e dividir pelo desvio padrão:

X_train_std = (X_train - np.mean(X_train))/np.std(X_train)

Em seguida, o mesmo deve ser feito com os atributos preditores do conjunto de testes, mas com padronização relativa ao conjunto de treinamento:

X_test_std = (X_test - np.mean(X_train))/np.std(X_train)

Se todo o conjunto X for utilizado na padronização, a rede neural receberá informações do conjunto de teste por meio da média e variância utilizada para preparar os dados de treinamento, o que não é desejável.


### Continuando

5. Treine uma rede neural multilayer perceptron para este problema com uma única camada e dez neurônios  
    5.1 Utilize a função de ativação ReLU  
    5.2 Utilize o solver Adam    
    5.3 Imprima o passo a passo do treinamento    
    5.4 Utilize o número máximo de épocas igual a 300  
6. Com o modelo em questão, após o treinamento, apresente:  
    6.1 Matriz de confusão para o conjunto de teste  
    6.2 Acurácia  
    6.3 F-Score  
    6.4 Precisão  
    6.5 Revocação  
7. Repita o treinamento da mesma rede anterior sem imprimir o passo a passo (verbose False) por 100 vezes  
    7.1 Cada uma destas repetições deve ser feita com uma nova partição Holdout  
    7.2 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino  
8. Repita por 100 vezes o treinamento desta mesma rede, mas utilizando o otimizador SGD  
    8.1 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino  
9. Houve influência da escolha do otimizador no desempenho da rede?

In [1]:
from google.colab import files
uploaded = files.upload()

Saving covtype.csv to covtype.csv


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

#### 1. Abra a base de dados em questão

In [3]:
data = pd.read_csv('covtype.csv')
data

Elevation  Aspect  Slope  ...  Soil_Type39  Soil_Type40  Cover_Type
0            2596      51      3  ...            0            0           5
1            2590      56      2  ...            0            0           5
2            2804     139      9  ...            0            0           2
3            2785     155     18  ...            0            0           2
4            2595      45      2  ...            0            0           5
...           ...     ...    ...  ...          ...          ...         ...
581007       2396     153     20  ...            0            0           3
581008       2391     152     19  ...            0            0           3
581009       2386     159     17  ...            0            0           3
581010       2384     170     15  ...            0            0           3
581011       2383     165     13  ...            0            0           3

[581012 rows x 55 columns]

#### 2. Elimine todas as colunas relativas aos atributos categóricos

In [4]:
#Armazenando nome de colunas a serem eliminadas em uma lista
columns_out = []

#Atributo área selvagem
for i in range(1, 5):
    columns_out.append('Wilderness_Area' + str(i))
    
#Atributo tipo de solo
for i in range(1, 41):
    columns_out.append('Soil_Type' + str(i))
    
data = data.drop(columns=columns_out)
data

Elevation  Aspect  ...  Horizontal_Distance_To_Fire_Points  Cover_Type
0            2596      51  ...                                6279           5
1            2590      56  ...                                6225           5
2            2804     139  ...                                6121           2
3            2785     155  ...                                6211           2
4            2595      45  ...                                6172           5
...           ...     ...  ...                                 ...         ...
581007       2396     153  ...                                 837           3
581008       2391     152  ...                                 845           3
581009       2386     159  ...                                 854           3
581010       2384     170  ...                                 864           3
581011       2383     165  ...                                 875           3

[581012 rows x 11 columns]

#### 3. Armazene o atributo alvo em uma variável y e os atributos preditores em uma variável X

In [5]:
#Dataframe apenas com os atributos preditores
data_atr = data.drop(columns=['Cover_Type'])

In [6]:
X = np.array(data_atr[0:])

y = data['Cover_Type'].to_numpy()

#### 4. Efetue uma partição holdout 70/30 com o sklearn, distribuindo os exemplos de maneira aleatória

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

#### 5. Efetue o escalonamento dos atributos

In [8]:
X_train_std = (X_train - np.mean(X_train))/np.std(X_train)

X_test_std = (X_test - np.mean(X_train))/np.std(X_train)

#### 6. Treine uma rede neural multilayer perceptron para este problema com uma única camada e dez neurônios  
    6.1 Utilize a função de ativação ReLU  
    6.2 Utilize o solver Adam    
    6.3 Imprima o passo a passo do treinamento    
    6.4 Utilize o número máximo de épocas igual a 300

In [9]:
clf = MLPClassifier(hidden_layer_sizes=(10,), max_iter=300, verbose=True).fit(X_train, y_train)

Iteration 1, loss = inf
Iteration 2, loss = 0.90639299
Iteration 3, loss = 0.83216724
Iteration 4, loss = 0.80365170
Iteration 5, loss = 0.78259645
Iteration 6, loss = 0.76449727
Iteration 7, loss = 0.75511517
Iteration 8, loss = 0.74939411
Iteration 9, loss = 0.74392805
Iteration 10, loss = 0.74122503
Iteration 11, loss = 0.73972374
Iteration 12, loss = 0.73801867
Iteration 13, loss = 0.73655748
Iteration 14, loss = 0.73602534
Iteration 15, loss = 0.73557247
Iteration 16, loss = 0.73412318
Iteration 17, loss = 0.73408303
Iteration 18, loss = 0.73548558
Iteration 19, loss = 0.73299803
Iteration 20, loss = 0.73372164
Iteration 21, loss = 0.73237045
Iteration 22, loss = 0.73304756
Iteration 23, loss = 0.73207107
Iteration 24, loss = 0.73123771
Iteration 25, loss = 0.73147585
Iteration 26, loss = 0.73103903
Iteration 27, loss = 0.73020623
Iteration 28, loss = 0.72962772
Iteration 29, loss = 0.72841169
Iteration 30, loss = 0.72799931
Iteration 31, loss = 0.72826782
Iteration 32, loss = 0.7

#### 7. Com o modelo em questão, após o treinamento, apresente:  
    7.1 Matriz de confusão para o conjunto de teste  
    7.2 Acurácia  
    7.3 F-Score  
    7.4 Precisão  
    7.5 Revocação  

In [10]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))

print("")
print("Acurácia: " + str(np.round(clf.score(X_test, y_test)*100, 4)) + "%")

precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
print("Precisão:",np.round(precision, 4))

recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
print("Revocação:",np.round(recall, 4))

fscore = 2 * (precision * recall) / (precision + recall)
print("F-Score:",np.round(fscore, 4))

[[44240 18809    68     0     0    11   422]
 [15749 66980  1638     0     0   483    30]
 [    0  1846  7993    52     0   828     0]
 [    0     2   713    86     0    28     0]
 [    4  2799    34     0     0     1     0]
 [    4  1492  2777    16     0   940     0]
 [ 5483    72     0     0     0     0   704]]

Acurácia: 69.3862%
Precisão: 0.6749
Revocação: 0.6939
F-Score: 0.6842


#### 8. Repita o treinamento da mesma rede anterior sem imprimir o passo a passo (verbose False) por 100 vezes  
    8.1 Cada uma destas repetições deve ser feita com uma nova partição Holdout  
    8.2 Apresente a média e o desvio padrão da acurácia e do F-Score para o conjunto de treino 

In [19]:
#numpy array para armzanear as acurácias
acurr_arr = np.array([])

#numpy array para armzanear os F-scores
fscore_arr = np.array([])

for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    
    clf = MLPClassifier(hidden_layer_sizes=(10,), max_iter=300, verbose=False).fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    acurr_arr = np.append(acurr_arr, clf.score(X_test, y_test))
    fscore_arr = np.append(fscore_arr, f1_score(y_test, y_pred, average='weighted'))
    
print("Acurácia")
print("Média:" + str(np.round(np.mean(acurr_arr), 4)))
print("Desvio padrão:" + str(np.round(np.std(acurr_arr), 4)))
print("")
print("F-Score")
print("Média:" + str(np.round(np.mean(fscore_arr), 4)))
print("Desvio padrão:" + str(np.round(np.std(fscore_arr), 4)))

Acurácia
Média:0.6981
Desvio padrão:0.0144

F-Score
Média:0.6835
Desvio padrão:0.0144


#### 9. Repita por 100 vezes o treinamento desta mesma rede, mas utilizando o otimizador SGD  

In [21]:
#numpy array para armzanear as acurácias
acurr_arr = np.array([])

#numpy array para armzanear os F-scores
fscore_arr = np.array([])

for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    
    clf = MLPClassifier(hidden_layer_sizes=(10,),solver='sgd', max_iter=300, verbose=False).fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    acurr_arr = np.append(acurr_arr, clf.score(X_test, y_test))
    fscore_arr = np.append(fscore_arr, f1_score(y_test, y_pred, average='weighted'))
    
print("Acurácia")
print("Média:" + str(np.round(np.mean(acurr_arr), 4)))
print("Desvio padrão:" + str(np.round(np.std(acurr_arr), 4)))
print("")
print("F-Score")
print("Média:" + str(np.round(np.mean(fscore_arr), 4)))
print("Desvio padrão:" + str(np.round(np.std(fscore_arr), 4)))

Acurácia
Média:0.4876
Desvio padrão:0.0011

F-Score
Média:0.3197
Desvio padrão:0.0012


#### 10. Houve influência da escolha do otimizador no desempenho da rede?

<div style="text-align: justify">
    Com o solver sgd, o treinamento levou bem menos tempo, mas em contrapartida, tanto a acurácia quanto o f-score foram nitidamente piores.
</div>

## Discussão

Nos passos anteriores, você avaliou o desempenho de uma única rede neural que contém os seguintes parâmetros: uma única camada oculta com 10 neurônios e função de ativação ReLU. O otimizador utilizado, quer seja SGD ou ADAM, trata-se do algoritmo para aproximar o gradiente do erro. Neste sentido, a escolha do otimizador é um hiperparâmetro, pois diz respeito a como a rede neural definida previamente atuará "em tempo de execução"  durante o processo de treinamento. Também são hiperparâmetros a quantidade de épocas, a taxa de aprendizado inicial, dentre outros.

Cabe alientar também que você efetuou o treinamento desta rede por 100 vezes e apresentou os resultados em termos de média +- desvio padrão. Lembre-se que em uma rede neural há a inicialização aleatória de pesos e, em consequência, o desempenho delas está sujeito à uma flutuação estocástica. A execução destas múltiplas vezes faz com que eliminemos algum viés introduzido por uma boa ou má "sorte" na escolha de pesos no caso de uma única execução.

Você também aprendeu uma estratégia para escalonar os atributos para uma melhor convergência da rede. Utilize-a em todos os treinamentos e testes propostos a seguir.

## Propondo Novas Arquiteturas

Variando  os parâmetros (uma ou duas camadas ocultas, com diferente números de neurônios em cada uma delas e a função de ativação) e o hiperparâmetros solver (Adam ou SGD) e o número de épocas (100,150 e 200), atenda ao que se pede:

1. Proponha 10 arquiteturas distintas de RNAs para o problema em questão, à sua escolha
2. Avalie cada uma das arquiteturas perante todos os hiperparâmetros apresentados por 100 vezes
3. Como resultado da avaliação, apresente:  
    3.1 Top-3 melhores redes no tocante à F-Score e Acurácia  
    3.2 Repetição em que houve o melhor desempenho de cada uma dessas redes: ilustre tp, tf, fp e fn  

## Estimando o número de neurônios

Um dos problemas de pesquisa com redes neurais artificiais consiste na determinação do número de neurônios em sua arquitetura. Embora não seja possível definir a priori qual rede neural é adequada para um problema, pois isto só é possível mediante uma busca exaustiva, há regras na literatura que sugerem o número de neurônios escondidos, tal como a regra da Pirâmide Geométrica, dada a seguir:

$$N_h = \alpha \cdot \sqrt{N_i \cdot N_o},$$

em que $N_h$ é o número de neurônios ocultos (a serem distribuídos em uma ou duas camadas ocultas), $N_i$ é o número de neurônios na camada de entrada e $N_o$ é o número de neurônios na camada de saída. 

1. Consulte a documentação da classe MLPClassifier (disponível em https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html) e obtenha os valores de $N_i$ e $N_h$.
2. Teste os valores de $\alpha$ como sendo iguais a $0.5$, $2$ e $3$.
3. Proponha pelo menos 30 redes neurais segundo a regra da pirâmide geométrica e teste-as nos mesmos termos estabelecidos anterioremente  (solver, épocas, etc.)  
    3.1 Apresente as top-3 melhores redes no tocante à F-Score e Acurácia  

## Testando as Redes Neurais com Atributos Categóricos

1. Considere as 6 redes neurais obtidas nos dois top-3 anteriores (arquiteturas próprias e regra da pirâmide geométrica)
2. Com todos os atributos preditores da base de dados original, incluindo os categóricos, treine e teste estas mesmas redes por 100 repetições  
    2.1 Considere o melhor otimizador para cada uma delas  
    2.2 Faça uso de 200 épocas para treinamento  
    2.2 Apresente os resultados de acurácia e F-Score em termos da média +- dp para cada arquitetura
3. Apresente o gráfico boxplot para o F-Score das 6 arquiteturas perante as 100 repetições

## Considerações Parciais

1. É possível identificar uma rede com desempenho superior às demais?
2. Qual estratégia mostrou-se mais producente para a obtenção de boas arquiteturas (Estratégia Própria ou Pirâmide Geométrica)? Por quê?
3. Considerar os atributos categóricos trouxe melhorias? Justifique.
4. Um número maior de épocas trouxe melhorias?
5. Qual a maior dificuldade de resolução do problema proposto perante as RNAs?